trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'artice-sc'
    appType: 'webApp'
    WebAppName: 'myarticlewebapp'
    deployToSlotOrASE: true
    ResourceGroupName: 'article-new-rg'
    SlotName: 'staging'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/*.zip'

- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'artice-sc'
    Action: 'Swap Slots'
    WebAppName: 'myarticlewebapp'
    ResourceGroupName: 'article-new-rg'
    SourceSlot: 'staging'
